export const categories = [
  { id: "all", label: "All", emoji: "⚡" },
  { id: "fantasy", label: "Fantasy Adventure", emoji: "🐉", group: "Features" },
  {
    id: "scifi",
    label: "Sci-Fi & Futuristic",
    emoji: "🚀",
    group: "Features",
  },
  {
    id: "suspense",
    label: "Horror & Thriller",
    emoji: "👻",
    group: "Features",
  },
  {
    id: "mystery",
    label: "Mystery & Detective",
    emoji: "🕵️",
    group: "Features",
  },
  {
    id: "romantic",
    label: "Romance (Light / Emotional)",
    emoji: "💕",
    group: "Features",
  },
  {
    id: "comingofage",
    label: "Coming-of-Age",
    emoji: "🌱",
    group: "Features",
  },
  {
    id: "moral",
    label: "Moral / Educational Stories",
    emoji: "📚",
    group: "Features",
  },
  {
    id: "historical",
    label: "Historical Mini Stories",
    emoji: "🏛️",
    group: "Features",
  },
  {
    id: "mythology",
    label: "Mythology Retellings",
    emoji: "⚡",
    group: "Features",
  },
  {
    id: "sliceoflife",
    label: "Slice of Life",
    emoji: "🌤️",
    group: "Features",
  },
  {
    id: "comedy",
    label: "Comedy / Humor",
    emoji: "😂",
    group: "Features",
  },
  {
    id: "survival",
    label: "Survival Stories",
    emoji: "🏕️",
    group: "Features",
  },
  {
    id: "inspirational",
    label: "Inspirational / Motivational",
    emoji: "✨",
    group: "Features",
  },
  {
    id: "crime",
    label: "Crime & Underworld",
    emoji: "🕶️",
    group: "Features",
  },
  {
    id: "superhero",
    label: "Superhero / Power Awakening",
    emoji: "🦸",
    group: "Features",
  },
  {
    id: "psychological",
    label: "Psychological Drama",
    emoji: "🧠",
    group: "Features",
  },
  {
    id: "ai",
    label: "AI & Technology Stories",
    emoji: "🤖",
    group: "Features",
  },
  {
    id: "kids",
    label: "Kids / Animated Stories",
    emoji: "🧸",
    group: "Features",
  },
  {
    id: "multiverse",
    label: "Alternate Reality / Multiverse",
    emoji: "🌌",
    group: "Features",
  },
  {
    id: "tragic",
    label: "Tragic / Emotional Drama",
    emoji: "💧",
    group: "Features",
  },
];

export const videos = [
    {
    id: 1,
    title: "Lumi and the Lost Colors",
    story: "Source: asset/Demo_Sample02_StoryMatrix.mp4",
    src: "/videos/final-demo-sample-audio-subtitle-storymatrix.mp4",
    thumbnail: "/team/dev-2.svg",
    duration: "0:43",
    durationSec: 43,
    category: "adventure",
    model: "StoryMatrix",
    resolution: "720p",
    hasAudio: true,
    hasSubtitle: true,
    tags: ["adventure", "magic", "animated", "colors"],
    date: "2026-04-19",
    storyJsonPath: "/stories/lumi-and-the-lost-colors.json",
  },
  {
    id: 2,
    title: "Robot And A Star",
    story: "Source: asset/Demo_Sample01_StoryMatrix.mp4",
    src: "/videos/demo-sample-01-storymatrix.mp4",
    thumbnail: "/team/dev-1.svg",
    duration: "0:12",
    durationSec: 12,
    category: "sci-fi",
    model: "StoryMatrix",
    resolution: "720p",
    hasAudio: false,
    hasSubtitle: false,
    tags: ["sci-fi", "robot", "star"],
    date: "2026-04-19",
  },
  {
    id: 3,
    title: "A boy with his magical Phoenix friend",
    story: "Source: asset/Demo_Sample02_StoryMatrix.mp4",
    src: "/videos/demo-sample-02-storymatrix.mp4",
    thumbnail: "/team/dev-2.svg",
    duration: "0:12",
    durationSec: 12,
    category: "fantasy",
    model: "StoryMatrix",
    resolution: "720p",
    hasAudio: false,
    hasSubtitle: false,
    tags: ["fantasy","Phoenix", "magic"],
    date: "2026-04-19",
  },

  {
    id: 4,
    title: "A boy and his fox friend ",
    story: "Source: asset/Demo_Sample02_StoryMatrix.mp4",
    src: "/videos/demo-sample-04-storymatrix.mp4",
    thumbnail: "/team/dev-2.svg",
    duration: "0:12",
    durationSec: 12,
    category: "adventure",
    model: "StoryMatrix",
    resolution: "720p",
    hasAudio: false,
    hasSubtitle: false,
    tags: ["adventure", "magic"],
    date: "2026-04-19",
  },
  {
    id: 5,
    title: "A robot exploring the universe",
    story: "Source: asset/Demo_Sample02_StoryMatrix.mp4",
    src: "/videos/demo-sample-03-storymatrix.mp4",
    thumbnail: "/team/dev-2.svg",
    duration: "0:12",
    durationSec: 12,
    category: "adventure",
    model: "StoryMatrix",
    resolution: "720p",
    hasAudio: false,
    hasSubtitle: false,
    tags: ["adventure", "magic"],
    date: "2026-04-19",
  },
];

export const modelComparisons = [
  {
    model: "STORYMATRIX-4D",
    color: "#9D4EDD",
    glowColor: "rgba(157,78,221,0.3)",
    fps: 30,
    resolution: "720p-1080p",
    input: "Text, Image, Audio, Depth",
    duration: "4+ min",
    maxLength: "4+ min",
    consistencyLabel: "TCI 0.84",
    control: "5-Agent MARL",
    coherence: 84,
    temporal: 81,
    narrative: 92,
    speed: 7.8,
    fvd: 344,
    ssim: 0.81,
    clipScore: 0.83,
    vbenchMotion: 59.3,
    tci: 0.84,
    humanNarrative: 4.6,
    humanCharacter: 4.5,
    humanCreative: 4.7,
    youtubeId: "dQw4w9WgXcQ",
    videoSrc: "/videos/final-demo-sample-audio-subtitle-storymatrix.mp4",
    badge: "Ours",
  },
  {
    model: "Open-Sora 2.0",
    color: "#4CC9F0",
    glowColor: "rgba(76,201,240,0.3)",
    fps: 24,
    resolution: "720p-1080p",
    input: "Text",
    duration: "~60 sec",
    maxLength: "~60 sec",
    consistencyLabel: "TCI 0.61",
    control: "Prompt-driven",
    coherence: 61,
    temporal: 72,
    narrative: 70,
    speed: 6.9,
    fvd: 412,
    ssim: 0.72,
    clipScore: 0.76,
    vbenchMotion: 55.0,
    tci: 0.61,
    youtubeId: "ZTidn2dBYbY",
    videoSrc: "/videos/open-sora-sample-01.mp4",
  },
  {
    model: "Wan 2.2",
    color: "#F72585",
    glowColor: "rgba(247,37,133,0.3)",
    fps: 30,
    resolution: "1080p",
    input: "Text, Image",
    duration: "~60 sec",
    maxLength: "~60 sec",
    consistencyLabel: "TCI 0.68",
    control: "Medium",
    coherence: 68,
    temporal: 75,
    narrative: 78,
    speed: 6.8,
    fvd: 380,
    ssim: 0.75,
    clipScore: 0.78,
    vbenchMotion: 58.4,
    tci: 0.68,
    humanNarrative: 3.1,
    humanCharacter: 3.3,
    humanCreative: 3.2,
    youtubeId: "3JZ_D3ELwOQ",
    videoSrc: "/videos/wan-2-2-sample-01.mp4",
  },
  {
    model: "HunyuanVideo",
    color: "#00F5FF",
    glowColor: "rgba(0,245,255,0.3)",
    fps: 24,
    resolution: "720p-1080p",
    input: "Text, Image",
    duration: "16-20 sec",
    maxLength: "16-20 sec",
    consistencyLabel: "TCI 0.65",
    control: "Medium",
    coherence: 65,
    temporal: 74,
    narrative: 77,
    speed: 6.4,
    fvd: 365,
    ssim: 0.74,
    clipScore: 0.77,
    vbenchMotion: 61.8,
    tci: 0.65,
    humanNarrative: 3.4,
    humanCharacter: 3.5,
    humanCreative: 3.3,
    youtubeId: "M7lc1UVf-VE",
    videoSrc: "/videos/hunyuan-sample-01.mp4",
  },
];

export const methodologySteps = [
  {
    step: 1,
    title: "Multimodal Input",
    desc: "Visual references and audio signals are collected as synchronized inputs for long-horizon generation.",
    icon: "📝",
    color: "#9D4EDD",
    tech: ["Vision Input", "Audio Input", "Frame Packs"],
  },
  {
    step: 2,
    title: "3D VCU Encoder",
    desc: "A 3D encoder projects visual and audio tokens into a unified latent space for spatio-temporal learning.",
    icon: "🎬",
    color: "#7B2FBE",
    tech: ["3D Encoder", "Latent Space", "Cross-Modal Fusion"],
  },
  {
    step: 3,
    title: "Prompt Engineering",
    desc: "A prompt refiner and patchify module reshape latent tokens into robust multimodal prompts.",
    icon: "⚡",
    color: "#4CC9F0",
    tech: ["Prompt Refiner", "Patchify", "Token Routing"],
  },
  {
    step: 4,
    title: "4D World Model",
    desc: "A DiT-based long-context transformer models scene dynamics across time, motion, and audio.",
    icon: "🖼️",
    color: "#3A86FF",
    tech: ["DiT Blocks", "LongCat Transformer", "Audio Block"],
  },
  {
    step: 5,
    title: "5-Agent MARL",
    desc: "QMIX, PPO, and GRPO style coordination agents optimize story, scene, and character consistency.",
    icon: "🔗",
    color: "#F72585",
    tech: ["QMIX", "PPO", "GRPO"],
  },
  {
    step: 6,
    title: "3D Decoder Output",
    desc: "The decoder converts optimized latents into coherent output videos with 720p-1080p quality.",
    icon: "🎥",
    color: "#FF6B35",
    tech: ["3D Decoder", "30fps", "C2PA Watermark"],
  },
];

export const architectureLayers = [
  {
    id: "vcu",
    stage: "01",
    title: "VCU Multimodal Encoder",
    desc: "Fuses text, image, audio, depth, and keypoints into one shared conditioning embedding consumed by every downstream module.",
    tech: ["7B VLM + LoRA", "Audio CLIP", "Unified Conditioning"],
    color: "#9D4EDD",
  },
  {
    id: "marl",
    stage: "02",
    title: "5-Agent MARL Planner",
    desc: "Director, Visual, Narrative, Audio-Reactive, and World agents coordinate through QMIX with centralized training and decentralized execution.",
    tech: ["QMIX", "CTDE", "Curriculum 8s to 5min"],
    color: "#F72585",
  },
  {
    id: "lwm",
    stage: "03",
    title: "4D Latent World Model",
    desc: "Maintains persistent sparse-voxel scene memory across shots so geometry and identity stay stable in long-horizon generation.",
    tech: ["Sparse Voxels", "Geometry Forecasting", "Continuity Memory"],
    color: "#3A86FF",
  },
  {
    id: "ctfe",
    stage: "04",
    title: "CTFE Memory Tokens",
    desc: "Cross-temporal memory tokens aggregate features from prior frames with O(n·k) complexity, avoiding full O(n²) long-context attention.",
    tech: ["Cross-Temporal Tokens", "Character Lock", "Story-State Recall"],
    color: "#00F5FF",
  },
  {
    id: "ode",
    stage: "05",
    title: "Continuous-Time Field Encoding",
    desc: "Neural ODE style dynamics model smooth motion across arbitrary frame rates and improve temporal stability in long sequences.",
    tech: ["Neural ODE", "Temporal Super-Resolution", "Smooth Dynamics"],
    color: "#4CC9F0",
  },
  {
    id: "dit",
    stage: "06",
    title: "STORYMATRIX-DiT (2B)",
    desc: "Final generation backbone with Sparse Temporal Fusion (STF) and Residual Latent Flow Predictor (RLFP) for efficient, coherent output.",
    tech: ["STF", "RLFP", "O(n^2) to O(n·k)"],
    color: "#FF6B35",
  },
];

export const architectureFlow = [
  "Text, image, audio, and depth input",
  "VCU encoding into shared latent conditioning",
  "Director-led multi-agent planning (MARL)",
  "Visual, Narrative, and Audio agent coordination",
  "4D world memory update with CTFE tokens",
  "STORYMATRIX-DiT generation with STF + RLFP",
  "Final video output and memory-to-video loop",
];

export const metrics = {
  fvd: 344,
  ssim: 0.81,
  clipScore: 0.83,
  tci: 0.84,
  vbenchMotion: "59.3%",
  maxLength: "4+ min",
  humanNarrative: 4.6,
  humanCharacter: 4.5,
  humanCreative: 4.7,
};
